# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: 'main'
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    versioning-strategy: increase
    commit-message:
      prefix: "⬆️ "
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
